[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  ". /opt/venv/bin/activate && playwright install-deps",
  ". /opt/venv/bin/activate && playwright install chromium"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --log-level info api:app"