[phases.setup]
nixPkgs = ["python312", "gcc"]
aptPkgs = [
  "libnss3",
  "libnspr4",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdrm2",
  "libdbus-1-3",
  "libxkbcommon0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libgbm1",
  "libasound2t64",
  "libatspi2.0-0",
  "libxshmfence1",
  "libpango-1.0-0",
  "libcairo2",
  "libpangocairo-1.0-0",
  "fonts-liberation",
  "libegl1",
  "libgles2"
]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  ". /opt/venv/bin/activate && playwright install chromium"
]

[start]
# Extended timeout with keep-alive to prevent Railway platform timeouts
cmd = ". /opt/venv/bin/activate && gunicorn --bind 0.0.0.0:$PORT --timeout 1800 --workers 1 --threads 4 --worker-class gthread --keep-alive 300 --graceful-timeout 120 --log-level info api:app"