[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 api:app"
