[build]
builder = "NIXPACKS"

[deploy]
startCommand = "playwright install-deps && playwright install chromium && gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --log-level info api:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10