[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pip install playwright && playwright install chromium && playwright install-deps && gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 api:app"
